version: "3.9"

services:
    test_db:
        image: postgres:15
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test_db
        ports:
            - "25433:5432" # Optional: local port for debugging
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test"]
            interval: 5s
            retries: 5

    test_app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.test
        environment:
            NODE_ENV: test
            DATABASE_URL: postgres://test:test@test_db:5432/test_db
        depends_on:
            test_db:
                condition: service_healthy
        command: >
            sh -c "sleep 10 && npx prisma db push && npm run dev"
