services:
    api:
        build:
            context: .
            target: dev
        container_name: ecom-api-dev
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - PORT=${PORT}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: ecom-db-dev
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:${POSTGRES_PORT}"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
