services:
    api:
        build:
            context: .
            target: dev
        container_name: ecom-api-dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db
        env_file:
            - .env

    db:
        image: postgres:15
        container_name: ecom-db-dev
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
