version: "3.9"

services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test_db
        ports:
            - "5433:5432" # Optional: local port for debugging
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test"]
            interval: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.test
        environment:
            NODE_ENV: test
            DATABASE_URL: postgres://test:test@db:5432/test_db
        depends_on:
            db:
                condition: service_healthy
        command: sh -c "npx prisma generate && npm run test"
